name=input("whats your name")
print("hello" + name)
age=input("how old are your...")
print("Im", age +"years old")
course=input("what are you pursuing")
print("im pursuing", course + "right now")
hobby=input("whats your hobby")
print("I love", hobby)